name: Deploy Frontend to unaux

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to unaux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.UNAUX_FTP_SERVER }}
          username: ${{ secrets.UNAUX_FTP_USER }}
          password: ${{ secrets.UNAUX_FTP_PASS }}
          local-dir: ./ 
          server-dir: /varta-n.unaux.com/htdocs/
